Fix logging polluting stdout space for mcp (#8)
* bugfix: print/log to sys.stderr insted of sys.stdout (#6)

Printing/logging sys.stdout causes initialization problems:

2025-08-04T17:31:34.484+02:00 DEBUG 43668 --- [mcp-tests] [pool-2-thread-1] io.modelcontextprotocol.spec.McpSchema   : Received JSON message: Topic 'MY_TOPIC' is marked as public. No authentication required.
2025-08-04T17:31:34.485+02:00 ERROR 43668 --- [mcp-tests] [pool-2-thread-1] i.m.c.transport.StdioClientTransport     : Error processing inbound message for line: Topic 'MY_TOPIC' is marked as public. No authentication required.

com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Topic': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 6]

* bugfix: print/log to sys.stderr insted of sys.stdout (#7)

Printing/logging sys.stdout causes initialization problems:

Error processing inbound message for line: Sending notification to http://server.example/TOPIC with Markdown formatting

* add logger class abstraction using console.error to prevent initialization issues

* update build files

* bump version and update readme and include github pull request template

---------

Co-authored-by: michalcamona <michal.camona@gmail.com>